// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKO1c76IlLy3LOVC2q3Ei-uwFMwn51osQ',
    appId: '1:556196467528:web:1ff377a53964862e32d97d',
    messagingSenderId: '556196467528',
    projectId: 'cloud-chat-fd207',
    authDomain: 'cloud-chat-fd207.firebaseapp.com',
    databaseURL: 'https://cloud-chat-fd207-default-rtdb.firebaseio.com',
    storageBucket: 'cloud-chat-fd207.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATxuAeFLBkgY-cAWzGFb5lUxIIcjW4Zvw',
    appId: '1:556196467528:ios:54ea6c8de1d844ef32d97d',
    messagingSenderId: '556196467528',
    projectId: 'cloud-chat-fd207',
    databaseURL: 'https://cloud-chat-fd207-default-rtdb.firebaseio.com',
    storageBucket: 'cloud-chat-fd207.appspot.com',
    iosClientId: '556196467528-naraltgr1bgldemr7mgohai254qa301n.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudChat',
  );
}
